config/routes.rb
Rails.application.routes.draw do
  resources :forms do
    member do
      get 'download_csv'
      get 'download_excel'
      get 'download_json'
    end
    resources :email_templates, only: [:new, :create, :edit, :update, :destroy]
  end
  resources :websites
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
  # 
  namespace :api do
    namespace :v1 do
      post 'forms/:form_id/data_entries', to: 'data_entries#create', as: 'form_data_entries'
      # resources :data_entries, only: [:index, :create, :update, :destroy]
    end
  end
  root "forms#index"
end

app/models/website.rb
class Website < ApplicationRecord
  has_many :forms, dependent: :nullify
  belongs_to :user

  # enum status: { active: 0, inactive: 1 }

  validates :name, presence: true
  validates :url, presence: true, format: URI::regexp(%w[http https])
  validates :status, presence: true, numericality: { only_integer: true }
end

app/controllers/websites_controller.rb
class WebsitesController < ApplicationController
  before_action :set_website, only: %i[ show edit update destroy ]

  # GET /websites or /websites.json
  def index
    @websites = current_user.websites
  end

  # GET /websites/1 or /websites/1.json
  def show
    @data_entries = @website.forms
  end

  # GET /websites/new
  def new
    @website = Website.new
  end

  # GET /websites/1/edit
  def edit
  end

  # POST /websites or /websites.json
  def create
    @website = current_user.websites.new(website_params)

    respond_to do |format|
      if @website.save
        format.html { redirect_to @website, notice: "Website was successfully created." }
        format.json { render :show, status: :created, location: @website }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @website.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /websites/1 or /websites/1.json
  def update
    respond_to do |format|
      if @website.update(website_params)
        format.html { redirect_to @website, notice: "Website was successfully updated." }
        format.json { render :show, status: :ok, location: @website }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @website.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /websites/1 or /websites/1.json
  def destroy
    @website.destroy!

    respond_to do |format|
      format.html { redirect_to websites_path, status: :see_other, notice: "Website was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_website
      @website = Website.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def website_params
      params.fetch(:website, {})
    end
end

app/helpers/websites_helper.rb
module WebsitesHelper
end

app/views/websites/_form.html.erb
<%= form_with(model: website) do |form| %>
  <% if website.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(website.errors.count, "error") %> prohibited this website from being saved:</h2>

      <ul>
        <% website.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/websites/_website.html.erb
<div id="<%= dom_id website %>">
</div>

app/views/websites/edit.html.erb
<% content_for :title, "Editing website" %>

<h1>Editing website</h1>

<%= render "form", website: @website %>

<br>

<div>
  <%= link_to "Show this website", @website %> |
  <%= link_to "Back to websites", websites_path %>
</div>

app/views/websites/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Websites" %>

<h1>Websites</h1>

<div id="websites">
  <% @websites.each do |website| %>
    <%= render website %>
    <p>
      <%= link_to "Show this website", website %>
    </p>
  <% end %>
</div>

<%= link_to "New website", new_website_path %>

app/views/websites/new.html.erb
<% content_for :title, "New website" %>

<h1>New website</h1>

<%= render "form", website: @website %>

<br>

<div>
  <%= link_to "Back to websites", websites_path %>
</div>

app/views/websites/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @website %>

<div>
  <%= link_to "Edit this website", edit_website_path(@website) %> |
  <%= link_to "Back to websites", websites_path %>

  <%= button_to "Destroy this website", @website, method: :delete %>
</div>